# Importando bibliotecas

In [1]:
import pandas as pd

# Criando classe para carregar/salvar/deletar dados
OBS: Estou fazendo com csv, porém essa classe provavelmente irá mudar quando fizermos integrações com os bancos dos clientes.

In [18]:
class conect_data:
    
    def load_table(location_table, name_table, type_table,encoding='ISO-8859-1',sep=';'):
        data = pd.read_csv(f'{location_table}/{name_table}.{type_table}', encoding=encoding, sep=sep)
        return data
    
    def save_table(location_table, name_table, type_table):
        data = pd.to_csv(f'{location_table}/{name_table}.{type_table}')
        return data
    
    def del_table():
        pass

In [21]:
conect_data.load_table('../../data/data_ingestion/', 'ingestion.itens_describe', 'csv')

,NUMERO_REGISTRO_PRODUTO,IDENTIFICADOR_DO_ITEM,NOME_PRODUTO,TIPO_PRODUTO,CATEGORIA_REGULATORIA,CLASSE_TERAPEUTICA
0,104540166,25000025416,(VITAMINAS A ) + ASSSOCIACÕES,MEDICAMENTO,SIMILAR,VITAMINAS E SUPLEMENTOS MINERAIS
1,119350001,25010171858,AC SALICILICO + AC BENZOICO + IODO,MEDICAMENTO,SIMILAR,ANTIMICOTICOS PARA USO TOPICO
2,100470305,25351022805,ALENDRONATO SODICO,MEDICAMENTO,SIMILAR,SUPRESSORES DA REABSORCAO OSSEA
3,104730021,25025007821,ARNICA MONTANA,MEDICAMENTO,FITOTERÁPICO,FITOTERAPICO SIMPLES
4,131750004,25351032631,ARNICA MONTANA L.,MEDICAMENTO,FITOTERÁPICO,FITOTERAPICO SIMPLES
...,...,...,...,...,...,...
29833,100850243,25351062205,BDEXBRAUN,MEDICAMENTO,SIMILAR,HIPNOTICOS
29834,100849958,25351365186,NACFLU,MEDICAMENTO,SIMILAR,EXPECTORANTES BALSAMICOS E MUCOLITICO
29835,138400003,25351439741,ORFADIN,MEDICAMENTO,NOVO,OUTROS PRODUTOS PARA O TRATO ALIMENTAR E METAB...
29836,101800412,25351726949,POMALYST,MEDICAMENTO,NOVO,AGENTE IMUNOSUPRESSOR
29837,135170067,25351564399,ibuprofeno,MEDICAMENTO,GENÉRICO,ANALGESICOS NAO NARCOTICOS

In [20]:
conect_data.load_table('../../data/data_ingestion/', 'ingestion.itens_input', 'csv')

,NUMERO_REGISTRO_PRODUTO,IDENTIFICADOR_DO_ITEM,NOME_PRODUTO,DATA_DE_PEDIDO_DO_ITEM,DATA_DE_ENTRADA_DO_ITEM,DATA_VENCIMENTO_REGISTRO,QUANTIDADE,CUSTO_DE_AQUISIÇÃO
0,104540166,25000025416,(VITAMINAS A ) + ASSSOCIACÕES,NaN,25/04/2000,01/04/2005,NaN,NaN
1,119350001,25010171858,AC SALICILICO + AC BENZOICO + IODO,NaN,19/05/2000,01/05/2005,NaN,NaN
2,100470305,25351022805,ALENDRONATO SODICO,NaN,04/06/2001,01/05/2006,NaN,NaN
3,104730021,25025007821,ARNICA MONTANA,NaN,19/03/2002,01/03/2007,NaN,NaN
4,131750004,25351032631,ARNICA MONTANA L.,NaN,01/07/2002,01/06/2007,NaN,NaN
...,...,...,...,...,...,...,...,...
29833,100850243,25351062205,BDEXBRAUN,NaN,29/07/2022,NaN,NaN,NaN
29834,100849958,25351365186,NACFLU,NaN,29/07/2022,01/07/2032,NaN,NaN
29835,138400003,25351439741,ORFADIN,NaN,29/07/2022,NaN,NaN,NaN
29836,101800412,25351726949,POMALYST,NaN,29/07/2022,NaN,NaN,NaN
29837,135170067,25351564399,ibuprofeno,NaN,29/07/2022,NaN,NaN,NaN

# Criando cálculo de classificação da curva ABC

# Definindo classe do cálculo da curva ABC